services:
  scanomatic:
    privileged: true
    build: .
    ports: ["5000:5000"]
    environment:
      - LOGGING_LEVEL=20
    volumes:
      - ${SOM_SETTINGS:-som-settings}:/root/.scan-o-matic
      - ${SOM_PROJECTS_ROOT:-som-projects}:/somprojects
      - /dev/bus/usb:/dev/bus/usb
    develop:
      watch:
        - path: .
          include:
            - scanomatic/**/*
            - images/**/*
            - data/config/**/*
            - bun.lock
            - package.json
            - vite.config.js
            - pyproject.toml
            - Dockerfile
          action: rebuild
volumes:
  som-projects:
  som-settings:
